version: "3.8"
services:
  postgres:
    image: postgres:latest
    env_file:
      - .env.example
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env.example
    ports:
      - "5050:80"
    depends_on:
      - postgres
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.example
    ports:
      - "3000:3000"
    depends_on:
      - postgres
volumes:
  postgres-data:
