version: "3.8"
services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my_network
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - my_network
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next-app
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - my_network
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres-data:
  data:
    external: true
networks:
  my_network:
    driver: bridge
