version: "3.8"
services:
  postgres:
    image: postgres:latest
    env_file:
      - .env.example
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my_network
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env.example
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - my_network
  next-app:
    image: mossarelladev/web-challenge
    container_name: next-app
    env_file:
      - .env.example
    ports:
      - "3000:3000"
    networks:
      - my_network

volumes:
  postgres-data:
  data:
    external: true
networks:
  my_network:
    name: my_network
    external: true
